maivthan:
  eventpublisher: 'http://13.68.251.41/eventpublisher/api/v1/'
server:
  port: 8081  
  servlet:
    context-path: /employee
spring:
  h2:
      console: 
        enabled: true      
        path: /console
        settings:
          webAllowOthers: true           
  datasource: 
        url: jdbc:h2:./employee-local-DB;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE   
        username: sa
        password:
        driverClass:  org.h2.Driver
  jpa: 
        hibernate:
          ddl-auto: update