apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: employee-deployment 
spec: 
  selector: 
    matchLabels: 
      app: employee 
  replicas: 1 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: employee 
    spec: 
      containers: 
      - name: employee 
        image: maivthanacrregistry.azurecr.io/employee:latest
        ports: 
        - containerPort: 80 
        env:
        - name: SPRING_PROFILES_ACTIVE 
          valueFrom:
            configMapKeyRef:
              name: environment 
              key: SPRING_PROFILES_ACTIVE 
      
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: employee-service 
spec: 
  selector: 
    app: employee 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: ClusterIP 

          