server:
  port: 8090
  servlet:
    context-path: /employee
spring:
  flyway:
      baselineOnMigrate: true
  h2:
      console: 
        enabled: true      
        path: /console
        settings:
          webAllowOthers: true           
  datasource: 
        url: jdbc:h2:mem:demo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE   
        username: sa
        password:
        driverClass:  org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none