CREATE TABLE WEB_ORDER_LOCATION
   (	WEB_COUNTRY VARCHAR(3) NOT NULL, 
	LOCATION BIGINT NOT NULL, 
	LOCTYPE VARCHAR(1) NOT NULL, 
	DISPATCH VARCHAR(1) DEFAULT 'N' NOT NULL, 
	PICKUP VARCHAR(1) DEFAULT 'N' NOT NULL, 
	AVAIL_SEARCH VARCHAR(1) DEFAULT 'N' NOT NULL, 
	PRIORITY SMALLINT DEFAULT 99 NOT NULL, 
	WH_BREAK_PACK_IND VARCHAR(1), 
	CAN_HOLD_GIFT_REG VARCHAR(1) DEFAULT 'N' NOT NULL, 
	REQUIRE_PAYMENT_CAPTURE VARCHAR(1) DEFAULT 'N' NOT NULL, 
	FREIGHT_RULE_TYPE VARCHAR(256) NOT NULL, 
	TRANSFER_TYPE VARCHAR(1) DEFAULT 'E' NOT NULL, 
	PERSONALISE VARCHAR(1) DEFAULT 'N' NOT NULL, 
	DISPATCH_POINT_NAME VARCHAR(250) NOT NULL);

CREATE TABLE WEB_RESERVED_STOCK
(
	LOCATION BIGINT NOT NULL, 
	LOCTYPE VARCHAR(1) NOT NULL, 
	ITEM INT NOT NULL,		
	QUANTITY INT NOT NULL,
	WEB_ORDER BIGINT NOT NULL,
	RECEIVE_TYPE VARCHAR(5),
	RECEIVE_REFERENCE BIGINT,
	WEBSITE_ADJ DECIMAL(12,4) NOT NULL
);

CREATE TABLE DJ_WEB_LOC_AVAIL_BUFFER_VALUES
   (	LOCATION BIGINT NOT NULL,
	LOC_TYPE VARCHAR(1) NOT NULL,
	BUFFER_DATE TIMESTAMP(0),
	SKU INT NOT NULL,
	AGED_BUFFER SMALLINT NOT NULL,
	NON_AGED_BUFFER SMALLINT NOT NULL,
	AGED_BUFFER_FLAG VARCHAR(1) NOT NULL,
	MINIMUM SMALLINT NOT NULL,
	BUFFER_MULTIPLIER DECIMAL(12,4) NOT NULL,
	CALCULATED_BUFFER SMALLINT NOT NULL,
	CNC_AGED_BUFFER SMALLINT,
	CNC_NON_AGED_BUFFER SMALLINT, 
	CNC_CALCULATED_BUFFER SMALLINT
);

CREATE TABLE DJ_WEB_AVAIL_BUFFER_VALUES
(	LOC_TYPE VARCHAR(1) NOT NULL,
	DEPT SMALLINT NOT NULL,
	CLASS SMALLINT NOT NULL,
	SUBCLASS SMALLINT NOT NULL,
	BUFFER_DATE TIMESTAMP(0),
	NETWORK_BUFFER SMALLINT NOT NULL,
	MINIMUM SMALLINT NOT NULL,
	BUFFER_MULTIPLIER DECIMAL(12,4) NOT NULL,
	CALCULATED_BUFFER SMALLINT NOT NULL
);

CREATE TABLE WEB_DEPT_LOC_EXCLUDE
(
	WEB_COUNTRY_ID VARCHAR(3) NOT NULL,
	FREIGHT_PROVIDER_KEY SMALLINT NOT NULL,
	DEPT SMALLINT NOT NULL,
	LOC_TYPE VARCHAR(1) NOT NULL,
	LOCATION BIGINT NOT NULL,
	EFFECTIVE TIMESTAMP(0), 
	EXPIRES TIMESTAMP(0), 
	EXCLUDE_TYPE VARCHAR(8)
);

CREATE TABLE WEB_LOC_UNAVAIL_ITEMS
   (	LOCATION BIGINT NOT NULL, 
	LOCTYPE VARCHAR(1) NOT NULL,
	ITEM INT NOT NULL, 
	EXPIRES TIMESTAMP(0) NOT NULL
);


  CREATE TABLE PERIOD
   (	SYSAVAIL SMALLINT NOT NULL ,
	VDATE TIMESTAMP(0) NOT NULL ,
	START_454_HALF TIMESTAMP(0) NOT NULL ,
	END_454_HALF TIMESTAMP(0) NOT NULL ,
	START_454_MONTH TIMESTAMP(0) NOT NULL ,
	MID_454_MONTH TIMESTAMP(0) NOT NULL ,
	END_454_MONTH TIMESTAMP(0) NOT NULL ,
	HALF_NO INT NOT NULL ,
	NEXT_HALF_NO INT NOT NULL ,
	CURR_454_DAY SMALLINT NOT NULL ,
	CURR_454_WEEK SMALLINT NOT NULL ,
	CURR_454_MONTH SMALLINT NOT NULL ,
	CURR_454_YEAR SMALLINT NOT NULL ,
	CURR_454_MONTH_IN_HALF SMALLINT NOT NULL ,
	CURR_454_WEEK_IN_HALF SMALLINT NOT NULL ); 